name: .NET

on:
   push:
      branches: ["master"]
   pull_request:
      branches: ["master"]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4
         - name: Setup .NET
           uses: actions/setup-dotnet@v4
           with:
              dotnet-version: 8.0.x
         - name: Restore dependencies
           run: dotnet restore ./back/PersonalPodcast/
         - name: Build
           run: dotnet build --no-restore ./back/PersonalPodcast/
         # Add steps for the second project below
         - name: Restore dependencies (Second Project)
           run: dotnet restore ./back/PersonalPodcast.Test/
         - name: Build (Second Project)
           run: dotnet build --no-restore ./back/PersonalPodcast.Test/
         #- name: Test (Second Project)
          # run: dotnet test --verbosity normal ./back/PersonalPodcast.Test/
